# Generated by Django 5.0.6 on 2024-05-10 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="person",
            name="interests",
            field=models.CharField(default="fill it", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="mail",
            field=models.CharField(default="abc@gmail.com", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.CharField(default="fill it", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(default="995055555", max_length=100),
        ),
    ]
