# Generated by Django 5.0.6 on 2024-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0002_person_date_of_birth_person_interests_person_mail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ImageField(
                default="profilepic.jpg", upload_to="person_images/"
            ),
        ),
    ]
