# Generated by Django 4.2.13 on 2024-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0003_person_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(
                default="default_person_image.jpg", upload_to="person_images/"
            ),
        ),
    ]
