# Generated by Django 4.2.13 on 2024-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0004_alter_person_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(
                blank=True,
                default="person_images/default_person_image.jpg",
                help_text="Allowed file types: png, jpg, jpeg, gif",
                null=True,
                upload_to="person_images/",
            ),
        ),
    ]
