# Generated by Django 4.2.13 on 2024-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0005_alter_person_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(default="Earth", max_length=500),
        ),
        migrations.AddField(
            model_name="person",
            name="instagram",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="linkedin",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="otp",
            field=models.CharField(default="000000", max_length=6),
        ),
        migrations.AddField(
            model_name="person",
            name="projects",
            field=models.CharField(default="Fun", max_length=500),
        ),
        migrations.AddField(
            model_name="person",
            name="pronouns",
            field=models.CharField(default="pronoun/pronoun", max_length=20),
        ),
        migrations.AddField(
            model_name="person",
            name="twitter",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="youtube",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
