# Generated by Django 4.2.13 on 2024-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0006_person_address_person_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="instagram",
            field=models.CharField(default="www.instagram.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="linkedin",
            field=models.CharField(default="www.linkedin.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter",
            field=models.CharField(default="www.x.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="youtube",
            field=models.CharField(default="www.youtube.com", max_length=100),
        ),
    ]
