# Generated by Django 4.2.13 on 2024-07-03 17:52

from django.db import migrations, models
import django.db.models.deletion
import rolodex.models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0007_alter_person_instagram_alter_person_linkedin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=rolodex.models.upload_to
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rolodex.person",
                    ),
                ),
            ],
        ),
    ]
