# Generated by Django 4.2.13 on 2024-07-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0008_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="image",
            new_name="profilepic",
        ),
    ]
