# Generated by Django 4.2.13 on 2024-07-09 13:36

from django.db import migrations, models
import rolodex.models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0009_rename_image_person_profilepic"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="codeu",
            field=models.CharField(default=rolodex.models.generate_code, max_length=6),
        ),
    ]
