# Generated by Django 4.2.13 on 2024-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0010_person_codeu"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="userself",
            field=models.BooleanField(default=False),
        ),
    ]
