# Generated by Django 4.2.13 on 2024-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0011_person_userself"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="education",
            field=models.CharField(default="College", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="ventures",
            field=models.CharField(default="Ventures", max_length=100),
        ),
    ]
